### ISSUE TITLE
What board is this for?

### ISSUE THREAD

**Issue by dglaude** [deshipu/circuitpython-tetris-displayio#1]
Hi,

What board is this code for (and what board has a Z button)?
I could not figure out, and I was missing the board.BUTTON_O but by changing to board.O it does work on uGame 10.

Thank you

My change (board.UP) is not in use and just replace the Z to keep the same order and mask:
```
buttons = gamepad.GamePad(
    digitalio.DigitalInOut(board.O),
    digitalio.DigitalInOut(board.X),
    digitalio.DigitalInOut(board.UP),
    digitalio.DigitalInOut(board.DOWN),
    digitalio.DigitalInOut(board.LEFT),
    digitalio.DigitalInOut(board.RIGHT),
)
#    digitalio.DigitalInOut(board.Z),

```

**Comment by deshipu** [comment]
PewPew M4
